### ISSUE TITLE
Named constructors

### ISSUE THREAD

**Issue by Chemaclass** [Chemaclass/typed-arrays#17]
- fromValues(mixed ...$values)
- fromArray(mixed[] $values)

**Comment by Tito-Kati** [comment]
This unfortunately does not convince me to implement it, at least not in this way, our current constructor behaves as the `fromArray` should behave, so I really find the following hits to the other constructor, to the `fromValues`:

1. I don't see a clear circumstance where you are going to need to use the `fromValues`, I put some examples:
- Any function, method, repository... will return arrays. So we would use the `fromArray`.
- It also does not give you a clear benefit if you use several sources to obtain the data and you want to join them before building the array.
```
ExampleList::fromValues ​​(... $source1, ...$ source2); # this is not better
new ExampleList ([... $source1, ...$ source2]); # that this.
```
- The user only save a few square brackets when creating the arrays.

2. `fromValues` would only work for lists, you don't have any way to pass keys for maps or arrays. Even if your intention is to build a list from an array which can have keys, you can always remove them very easily with a native function before or during construction with `array_values`:
```
new ExampleList(array_values​​($source));
```

I really do not think it is worth having more code to maintain, for what it really contributes I advocate not implementing this and having a less and simpler code.

If I have missed any reason for the disadvantage or benefit of `fromValues`, please comment it to have all the information available to see if it is really worth implementing this.
