### ISSUE TITLE
Think about improving the class naming

### ISSUE THREAD

**Issue by Chemaclass** [Chemaclass/typed-arrays#6]
Singular vs Plural. For example:
- ArrayOfInteger vs ArrayOfIntegers

Think about possible edge cases or corners where this name convention might doesn't work. What other possibilities do we have?

**Comment by Tito-Kati** [comment]
- IntegersArray

Just to see the world burn, and that we have to rethink even the name of the repository.

**Comment by JesusValera** [comment]
I propose the following way:
1. `Immutable` or `Mutable`
2. Type (scalar or `object`)
3. `Map` or `List`

ex:
`MutableIntegerList`
`ImmutableBooleanMap`

**BUT** (more complex with non-scalar objects)
`ImmutableUserList` ?? How can we build this? Maybe dynamically? 👀 

Other possibility using this pattern (but this is not natural language)
`ImmutableListUser` or `MutableMapString` ...

What do you think @Tito-Kati @Chemaclass ?
